channels:
  - conda-forge

dependencies:
  - python=3.7.5
  - faker=13.7.0
  - pip=20.1
  - pip:
      - rpaframework==14.1.0 # https://rpaframework.org/releasenotes.html
      - rpaframework-aws==2.0.1
